version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      # Add default Kodiak `merge.automerge_label`
      - "automerge"
