name: pipeline

on:
  pull_request:
    branches:
      - "release-*"
      - "master"
    tags-ignore:
      - "*"

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: webpage install, build, and test
        uses: actions/setup-node@v2

      - run: yarn install --prefer-offline
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        id: install

      - run: npm i -g lerna
        id: lerna

      - run: yarn run build
        id: turbo
